name: 🚀 Build & Push Frontend to Scaleway

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-app:
    name: 🏗️ Build APP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Scaleway Container Registry
        run: echo "${{ secrets.SCW_SECRET_KEY }}" | docker login rg.fr-par.scw.cloud -u nologin --password-stdin

      - name: Inject VITE_API_URL
        run: echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > front/.env.production

      - name: Build and push APP image
        run: |
          docker build -t rg.fr-par.scw.cloud/namespace-theo-stoffelbach-final/my-front:latest ./front
          docker push rg.fr-par.scw.cloud/namespace-theo-stoffelbach-final/my-front:latest

  deploy-app:
    name: Deploy APP
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Install Scaleway CLI
        run: |
          # Téléchargement direct du binaire depuis GitHub releases  
          VERSION="2.41.0"
          wget -O scw "https://github.com/scaleway/scaleway-cli/releases/download/v${VERSION}/scaleway-cli_${VERSION}_linux_amd64"
          chmod +x scw
          sudo mv scw /usr/local/bin/scw
          scw version

      - name: Configure Scaleway CLI
        run: |
          scw config set access-key ${{ secrets.SCW_ACCESS_KEY }}
          scw config set secret-key ${{ secrets.SCW_SECRET_KEY }}
          scw config set default-project-id ${{ secrets.SCW_PROJECT_ID }}
          scw config set default-region fr-par

      - name: Update frontend container image
        run: |
          scw container container update ${{ secrets.SCW_FRONT_CONTAINER_ID }} image=rg.fr-par.scw.cloud/namespace-theo-stoffelbach-final/my-front:latest
