name: 🚀 Build & Push Frontend to Scaleway

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-app:
    name: 🏗️ Build APP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Scaleway Container Registry
        run: echo "${{ secrets.SCW_SECRET_KEY }}" | docker login rg.fr-par.scw.cloud -u nologin --password-stdin

      - name: Inject VITE_API_URL
        run: echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > front/.env.production

      - name: Build and push APP image
        run: |
          docker build -t rg.fr-par.scw.cloud/namespace-theo-stoffelbach-final/my-front:latest ./front
          docker push rg.fr-par.scw.cloud/namespace-theo-stoffelbach-final/my-front:latest

  deploy-app:
    name: Deploy APP
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Install Scaleway CLI
        run: |
          # Téléchargement direct du binaire depuis GitHub releases  
          VERSION="2.41.0"
          wget -O scw "https://github.com/scaleway/scaleway-cli/releases/download/v${VERSION}/scaleway-cli_${VERSION}_linux_amd64"
          chmod +x scw
          sudo mv scw /usr/local/bin/scw
          scw version

      - name: Configure Scaleway CLI
        run: |
          scw config set access-key ${{ secrets.SCW_ACCESS_KEY }}
          scw config set secret-key ${{ secrets.SCW_SECRET_KEY }}
          scw config set default-project-id ${{ secrets.SCW_PROJECT_ID }}
          scw config set default-region fr-par

      - name: Deploy or update frontend container
        run: |
          # Récupérer l'ID du namespace
          NAMESPACE_ID=$(scw container namespace list -o json | jq -r '.[] | select(.name=="namespace-theo-stoffelbach-final") | .id')

          if [ -z "$NAMESPACE_ID" ]; then
            echo "❌ Namespace non trouvé!"
            exit 1
          fi

          echo "✅ Namespace ID: $NAMESPACE_ID"

          # Vérifier si le container existe déjà
          CONTAINER_ID=$(scw container container list namespace-id=$NAMESPACE_ID -o json | jq -r '.[] | select(.name=="frontend-web") | .id // empty')

          if [ -z "$CONTAINER_ID" ]; then
            echo "🆕 Création du container frontend..."
            CONTAINER_ID=$(scw container container create \
              namespace-id=$NAMESPACE_ID \
              name=frontend-web \
              registry-image=rg.fr-par.scw.cloud/namespace-theo-stoffelbach-final/my-front:latest \
              port=80 \
              min-scale=0 \
              max-scale=3 \
              memory-limit=256 \
              cpu-limit=250 \
              privacy=public \
              -o json | jq -r '.id')
            echo "✅ Container créé: $CONTAINER_ID"
          else
            echo "🔄 Mise à jour du container existant: $CONTAINER_ID"
            scw container container update \
              container-id=$CONTAINER_ID \
              registry-image=rg.fr-par.scw.cloud/namespace-theo-stoffelbach-final/my-front:latest
          fi

          # Déployer le container
          echo "🚀 Déploiement du container..."
          scw container container deploy container-id=$CONTAINER_ID

          # Attendre et afficher l'URL
          sleep 10
          CONTAINER_URL=$(scw container container get container-id=$CONTAINER_ID -o json | jq -r '.domain_name')
          echo "✅ Frontend déployé: https://$CONTAINER_URL"
